// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKYTwqcbjUwopKbsHhsSuq9eu1ZQ6Hc8c',
    appId: '1:203318599334:web:b15596109ad0ac7e135e67',
    messagingSenderId: '203318599334',
    projectId: 'digital-health-care-ca243',
    authDomain: 'digital-health-care-ca243.firebaseapp.com',
    storageBucket: 'digital-health-care-ca243.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCacGLACdSjG5iJA4lCauaqbqQ_i5yB9k0',
    appId: '1:203318599334:android:92c3d4b3997e8f72135e67',
    messagingSenderId: '203318599334',
    projectId: 'digital-health-care-ca243',
    storageBucket: 'digital-health-care-ca243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnz8EveIY8rgorVgjb2x-isz5q7WvKEmA',
    appId: '1:203318599334:ios:6cd7beab7b5b60a4135e67',
    messagingSenderId: '203318599334',
    projectId: 'digital-health-care-ca243',
    storageBucket: 'digital-health-care-ca243.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnz8EveIY8rgorVgjb2x-isz5q7WvKEmA',
    appId: '1:203318599334:ios:6cd7beab7b5b60a4135e67',
    messagingSenderId: '203318599334',
    projectId: 'digital-health-care-ca243',
    storageBucket: 'digital-health-care-ca243.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKYTwqcbjUwopKbsHhsSuq9eu1ZQ6Hc8c',
    appId: '1:203318599334:web:930d84113d5a4ec7135e67',
    messagingSenderId: '203318599334',
    projectId: 'digital-health-care-ca243',
    authDomain: 'digital-health-care-ca243.firebaseapp.com',
    storageBucket: 'digital-health-care-ca243.firebasestorage.app',
  );
}
